name: Manual pytest for mac os

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_tests.txt

    - name: run pytest
      run: |
        pytest --junitxml=pytest_report.xml

    - name: generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: MacOS Tests
        path: pytest_report.xml
        reporter: jest-junit